print_settings.settings.*:
  type: config_object
  label: 'Print settings'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    pageH:
      type: number
      label: 'page height'
    pageW:
      type: number
      label: 'page width'
    marginT:
      type: number
      label: 'printer margin top'
    marginB:
      type: number
      label: 'printer margin bottom'
    marginW:
      type: number
      label: 'printer margin width' # on fait du recto verso => on prend la marge max gauche/droite pour les 2 cotés.
    versoOffsetY:
      type: number
      label: 'printer offset Y for verso'
    versoOffsetX:
      type: number
      label: 'printer offset X for verso'
    cardH:
      type: number
      label: 'card height'
    cardW:
      type: number
      label: 'card width'
    cardLandscape:
      type: boolean
      label: 'Imprimer les cartes en mode paysage'
    cardFold:
      type: boolean
      label: 'Imprimer des cartes pliées'
    traitCoupe:
      type: number
      label: 'taille des traits de coupe'